<?xml version='1.0' encoding='utf-8'?>
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>likec4</string>
        <key>scopeName</key>
        <string>source.likec4</string>
        <key>fileTypes</key>
        <array>
            <string>.c4</string>
            <string>.likec4</string>
            <string>.like-c4</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(link|icon):?\s+([^\s]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.property.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.single.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.likec4</string>
                <key>match</key>
                <string>\b(specification|model|views)\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(true|false)\b</string>
                <key>name</key>
                <string>constant.language.likec4</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(element|tag|relationship)\s+([^\s]+)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.class.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(opacity):?\s+([^\s]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.property.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(include|exclude)\s+(element\.kind|element\.tag)\s*(==|\!=|=)\s*([a-zA-Z#][_\*\.\w]*)\b
                </string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.symbol.likec4</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(actor|component|system|container|service|include|exclude|extend)\s+([a-zA-Z][_\*\.\w]*)\b
                </string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(navigateTo)\s+([_\*\.\w]+)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.likec4</string>
                <key>match</key>
                <string>\b(include|exclude)\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(shape|color|head|tail|line|border):?\s+(\w+)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.property.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.class.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.class.likec4</string>
                <key>match</key>
                <string>\b(TopBottom|LeftRight|BottomTop|RightLeft|xsmall|xs|small|sm|medium|md|large|lg|xl|xlarge)\b
                </string>
            </dict>
            <dict>
                <key>name</key>
                <string>entity.name.class.likec4</string>
                <key>match</key>
                <string>\b(amber|blue|gray|green|indigo|muted|primary|secondary|red|sky|slate|none)\b</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(title|description|technology|notation|multiple|padding|size|textSize|prop\d*):?\b</string>
                <key>name</key>
                <string>variable.parameter.function.likec4</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b([^\W]+)\s*(=)\s*([^\W]+)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(view)\s+([^\W]+)\s+(of|extends)\s+([a-zA-Z][_\.\w]*)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(view)\s+(of)\s+([a-zA-Z][_\.\w]*)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(view)\s+([_\.\w]*)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(it|this)\s+(-&gt;|-\[\w+\]-&gt;)\s+([^\W]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.function.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>(\b[_\.\w]+|\*)\s+(&lt;?-&gt;|-\[\w+\]-&gt;)\s+([_\.\w]+)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.likec4</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\b([\.\w]+)\s+(with)\s+\{</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>match</key>
                <string>\s+(&lt;?-&gt;|&lt;-|-\[\w+\]-&gt;)\s+([a-zA-Z][_\.\w]*)\b</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>storage.type.function.likec4</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.other.constant.likec4</string>
                <key>match</key>
                <string>#[^\s]+\b</string>
            </dict>
            <dict>
                <key>name</key>
                <string>storage.type.function.likec4</string>
                <key>match</key>
                <string>(&lt;?-&gt;|&lt;-)</string>
            </dict>
            <dict>
                <key>name</key>
                <string>variable.other.constant.likec4</string>
                <key>match</key>
                <string>
                    \b(customer|bigbank|singlePageApplication|mobileApp|apiApplication|mainframe|email|internetBankingSystem|cloud|ui|backend|auth|web|frontend|api|webApp|authService|messageBroker)\b
                </string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.likec4</string>
                <key>match</key>
                <string>
                    \b(BottomTop|LeftRight|RightLeft|TopBottom|autoLayout|browser|metadata|mobile|actor|color|cylinder|description|environment|deployment|deploymentNode|dynamic|global|group|element|exclude|extends|extend|include|instance(Of)?|it|model|muted|notation|node|notes|of|parallel|par|person|predicateGroup|predicate|primary|queue|rectangle|secondary|shape|specification|storage|styleGroup|style|tag|technology|this|title|view|views|where|source|target|with|zone)\b
                </string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\b\.)?(\*|_),?</string>
                <key>captures</key>
                <dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.constant.likec4</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>string.quoted.double.likec4</string>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string-character-escape</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>name</key>
                <string>string.quoted.single.likec4</string>
                <key>begin</key>
                <string>'</string>
                <key>end</key>
                <string>'</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>include</key>
                        <string>#string-character-escape</string>
                    </dict>
                </array>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.block.likec4</string>
                        <key>begin</key>
                        <string>/\*</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.likec4</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>\*/</string>
                        <key>endCaptures</key>
                        <dict>
                            <key>0</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.definition.comment.likec4</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>begin</key>
                        <string>//</string>
                        <key>beginCaptures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>punctuation.whitespace.comment.leading.likec4</string>
                            </dict>
                        </dict>
                        <key>end</key>
                        <string>(?=$)</string>
                        <key>name</key>
                        <string>comment.line.likec4</string>
                    </dict>
                </array>
            </dict>
            <key>string</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double.likec4</string>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#string-character-escape</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.single.likec4</string>
                        <key>begin</key>
                        <string>'</string>
                        <key>end</key>
                        <string>'</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#string-character-escape</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>string-character-escape</key>
            <dict>
                <key>name</key>
                <string>constant.character.escape.likec4</string>
                <key>match</key>
                <string>
                    \\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|u\{[0-9A-Fa-f]+\}|[0-2][0-7]{0,2}|3[0-6][0-7]?|37[0-7]?|[4-7][0-7]?|.|$)
                </string>
            </dict>
        </dict>
    </dict>
</plist>
